version: '2.0 beta1'
author: Yakamara Media GmbH & Co. KG
supportpage: www.prozer.org

requires:
  addons:
    xform:
      min-version: '3.0'
      plugins:
        manager:
          min-version: '2.8'