package: prozer
version: '2.0 beta8'
author: Yakamara Media GmbH & Co. KG
supportpage: www.prozer.org
package: prozer

requires:
  addons:
    xform:
      min-version: '3.0.3'
      plugins:
        manager:
          min-version: '3.0.3'